# Environment variables
env = EDITOR,nvim

# Core services
#exec-once = elephant                                      # App launcher backend (for walker)

# Extra autostart processes
# exec-once = uwsm app -- my-service

#exec-once = uwsm app -- waybar
exec-once = check-status
exec-once = check-agents-sync
#exec-once = uwsm app -- 1password
exec-once = uwsm app -- bitwarden-desktop
# exec-once = uwsm app -- voxtype daemon
