# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

# meta
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# apps
bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = CTRL SHIFT, escape, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- 1password

# web apps
# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, SPACE
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu

# Special workspace toggles
bind = SUPER, D, togglespecialworkspace, vesktop
bind = SUPER, M, togglespecialworkspace, music
bind = SUPER, odiaeresis, togglespecialworkspace, terminal #odiaeresis=Ö

# Window rules so apps always spawn into their special workspace
# Vesktop (Discord client)
windowrule {
  name = windowrule-1
  workspace = special:vesktop
  match:class = ^(vesktop)$
}

windowrule {
  name = windowrule-2
  workspace = special:vesktop
  match:class = ^(Vesktop)$
}


# Spotify
windowrule {
  name = windowrule-3
  workspace = special:music
  match:class = ^(spotify)$
}

windowrule {
  name = windowrule-4
  workspace = special:music
  match:class = ^(Spotify)$
}


# Vim-style focus movement
unbind = SUPER, J
unbind = SUPER, K
bind = SUPER, h, movefocus, l
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
bind = SUPER, l, movefocus, r

